### ISSUE TITLE
Should we support ruby 2.2.2 in travis?

### ISSUE THREAD

**Issue by vfonic** [spark-solutions/spree_shopify_importer#10]
I've noticed that we currently don't have ruby 2.2.2 as our lowest ruby version for travis builds. I think we should change that.

**Comment by krzysiek1507** [comment]
I think we should test against the newest version from line so 2.2.7, 2.3.4 and 2.4.1

**Comment by vfonic** [comment]
I agree the oldest supported version should be 2.2.7. However, I'd also say we should support the lowest ruby version that spree supports. This extension should ideally follow spree's requirements for ruby (and rails). Looking from that point of view, we should support 2.2.2 and let spree contributors take care and provide guidelines of which lowest ruby version to support IMO.

**Comment by vfonic** [comment]
Plus there's probably not much difference between 2.2.2 and 2.2.7 as ruby started following more semantic versioning.
