### ISSUE TITLE
Handling Users without Addresses

### ISSUE THREAD

**Issue by KajZukowski** [spark-solutions/spree_shopify_importer#119]

**Comment by jeniaefimov** [comment]
@KajZukowski could you please add more info to this issue description

**Comment by KajZukowski** [comment]
Example to handle: https://spree-products-importer.myshopify.com/admin/customers/2750953521251
This customer should be imported as well, despite having no addresses or orders.

**Comment by KajZukowski** [comment]
Seems to be working properly now. Closing for now, but will keep an eye out for this one in the future
