### ISSUE TITLE
Error 500 on trying to access "Items" / Specific User

### ISSUE THREAD

**Issue by KajZukowski** [spark-solutions/spree_shopify_importer#145]
https://spree-shopify-importer-test.herokuapp.com/admin/users/2/items

User affected: kz+test@sprks.eu

**Comment by jeniaefimov** [comment]
the problem with one of the orders of this user.
pause working on this one, until fix orders import.

**Comment by jeniaefimov** [comment]
@KajZukowski I'll rerun import today's evening and you can test it tomorrow.
I'll notify you.

**Comment by jeniaefimov** [comment]
ready for check
