### ISSUE TITLE
Order #1002 differences

### ISSUE THREAD

**Issue by KajZukowski** [spark-solutions/spree_shopify_importer#146]
Order #1002 is partially fulfilled and has 2 products in Shopify. In Spree Order view, that Order has only 1 product.

**Comment by jeniaefimov** [comment]
for now I see in shopify that it's `unfulfilled` order and has only 1 product.
@KajZukowski let's close this task and return back to this problem when we find it again.

**Comment by jeniaefimov** [comment]
https://spree-products-importer.myshopify.com/admin/orders/1692105343075

**Comment by KajZukowski** [comment]
There must have been a change in the admin panel. Nevertheless, I'm closing the ticket. I'll re-open it or write a new one after we run a new import and do regression tests.
