### ISSUE TITLE
Error when importing orders with pending payment

### ISSUE THREAD

**Issue by joaray** [spark-solutions/spree_shopify_importer#193]
Retro steps:
1. open console of the shop (locally or on Heroku)
2. set credentials and connect with Shopify API:
`api_key = ...
password = ...
shop_domain = ...
api_version = ...`

`credentials = {
  api_key: api_key,
  password: password,
  shop_domain: shop_domain,
  api_version: api_version
}`
`SpreeShopifyImporter::Connections::Client.instance.get_connection(credentials)`

3. Try to import an order with pending payment e.g. 1035:

`resource = ShopifyAPI::Order.find(1995375247459)
SpreeShopifyImporter::Importers::OrderImporter.new(resource.attributes.to_json).import!`

4. observe the error:

`ActiveRecord::RecordInvalid (Validation failed: State is invalid, Payment State is not included in the list)`

**Comment by jeniaefimov** [comment]
thanks for good task description!
