### ISSUE TITLE
Why we store OptionType and OptionValue with lowercase name?

### ISSUE THREAD

**Issue by vfonic** [spark-solutions/spree_shopify_importer#31]
I just noticed that we always `downcase` option types and option values. On this way we're losing some information from Shopify and make the resulting options always presented/stored in downcase.

I think we should store the options in the same case as they come from Shopify.

/cc @Argonus 

https://github.com/spark-solutions/spree_shopify_importer/blob/eaad16ee5399a1b5b458b4f098801ad89b0becfe/app/services/shopify_import/creators/product.rb#L41

https://github.com/spark-solutions/spree_shopify_importer/blob/eaad16ee5399a1b5b458b4f098801ad89b0becfe/app/services/shopify_import/data_parsers/products/base_data.rb#L25

**Comment by vfonic** [comment]
We should only downcase `OptionType.name` attribute as that's the only one that's not case sensitive: https://github.com/spree/spree/blob/master/core/app/models/spree/option_type.rb#L16

**Comment by Argonus** [comment]
Will be fixed in https://github.com/spark-solutions/spree_shopify_importer/pull/99
